name: Build and deploy Python app to Azure Web App - nayamode-msft-webchat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      # Setup Node.js for frontend build
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
          
      # Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
          
      # Build frontend assets
      - name: Build frontend
        run: |
          cd frontend
          npm run build
          cd ..

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      # Create an optimized deployment package
      - name: Prepare deployment package
        run: |
          # Create a clean directory for deployment
          mkdir -p deploy_package
          
          # Copy only necessary backend files
          cp -r *.py deploy_package/
          cp requirements.txt deploy_package/
          cp -r static deploy_package/ || true
          cp -r templates deploy_package/ || true
          
          # Copy the built frontend files (adjust path as needed)
          mkdir -p deploy_package/static/frontend
          cp -r frontend/build/* deploy_package/static/frontend/ || true
          
          # Create a ZIP archive for faster upload
          cd deploy_package
          zip -r ../deploy_package.zip .
      
      # Deploy directly to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'nayamode-msft-webchat'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F2E4FF334F3A47E3BFDF0E55660689CE }}
          package: deploy_package.zip
          deployment-method: zip
